### PR TITLE
[FEATURE] Add random sorting to expert mode

### PR DESCRIPTION
**Pull request by kersten**
Added a checkbox to enable simple random slides.

Actually this pull only selects a random starting point for the slider. A more random option would be to sort the fal images randomly on every request. But this would also slow down the site, because the caching has to be turned off.

This could be done by using ```v:render.uncached```.

I don’t know, but should ```v:iterate.random``` work for this?

### CODE REVIEW

**Comment by kersten** [comment]
I hope I have got it now.

These changes are able to select which type of randomiser you want to use. There are the only JS randomiser und the vhs randomiser, which is sorting the images in RAND ```v:interator.sort```

Sorry for the many commits, but my test system was on a remote server ;)

If there is something missing, just ask me for that.

**Comment by misterboe** [comment]
hey @kersten, thanks for your support. i will test this asap. Nice feature.

**Comment by misterboe** [comment]
It seems to work everything as it should.  But could you please Create a new PR with only one commit massage and all the changes inside. ```[FEATURE] Add random sorting to expert mode```

**Comment by kersten** [comment]
Ok, took me some tries, but I think I got it now.

**Pull request merged**
